name: Tests

on:
  pull_request:
    branches:
      - main

# Cancel any active builds when new commits are pushed
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  JEST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run CI
        run: npm ci

#      - name: Run Tests
#        run: npm run test
#
#      - name: Publish Results
#        uses: dorny/test-reporter@v1
#        if: always()
#        with:
#          name: JS Report
#          path: "reports/*.xml"
#          reporter: jest-junit
